services:
  server:
    image: plugnik
    container_name: plugnik
    ports:
      - "80:80"
    volumes:
      - ./server/updatePlugins.xml:/updatePlugins.xml
      - /tmp/plugins/:/tmp/plugins # Should be pointing to storage machine
      - ./settings/plugin_manager.prod.json:/app/settings/plugin_manager.json
