services:
  server:
    image: jetbrain-plugin-repository
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plugins
    ports:
      - "80:80"
    volumes:
      - ./updatePlugins.xml:/updatePlugins.xml
      - ./server:/app/server/
    command: uvicorn server:app --reload --host 0.0.0.0 --port 80