services:
  server:
    image: plugnik
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plugnik
    ports:
      - "80:80"
    volumes:
      - ./server/updatePlugins.xml:/updatePlugins.xml
      - ./server:/app/server/  # Mounting the server, so it will still reload inside the container
      - ./settings/plugin_manager.dev.json:/app/settings/plugin_manager.json
    command: uvicorn server:app --reload --host 0.0.0.0 --port 80